import { createApp } from "vue";
import App from "./App.vue";
import vuetify from "./plugins/vuetify";
import { loadFonts } from "./plugins/webfontloader";
import router from "./router";
import "bootstrap/dist/css/bootstrap.min.css";
import "./registerServiceWorker";
import db from "./firebase/init.js";
import "bootstrap/dist/js/bootstrap.js";
loadFonts();
createApp(App).use(vuetify).use(router).mount("#app"), use(db);
